[book]
authors = ["Eric Hutchins"]
language = "en"
src = "src"
title = "geoipsed"
description = "Extraction and inline decoration of IPv4 and IPv6 addresses"

[output.html]
git-repository-url = "https://github.com/erichutchins/geoipsed"
edit-url-template = "https://github.com/erichutchins/geoipsed/edit/main/docs/{path}"
